/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Final.ui.abm;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import Final.controladores.JugadorControlador;
import Final.controladores.PosicionControlador;
import Final.objetos.Jugador;
import Final.objetos.Posicion;
import Final.ui.grilla.GrillaJugador;

/**
 *
 * @author Gaston
 */
public class AbmJugador extends javax.swing.JInternalFrame {

    /**
     * Creates new form AbmJugador
     */
    
    private GrillaJugador grillaJugador;
    private JugadorControlador jugadorControlador;
    private PosicionControlador posicionControlador;
    private DefaultComboBoxModel modelCombo;
    
    public AbmJugador() {
        initComponents();
        
        jugadorControlador = new JugadorControlador();
        posicionControlador = new PosicionControlador();
        
        try 
        {
            grillaJugador = new GrillaJugador(jugadorControlador.listar());
            jtListadoJugador.setModel(grillaJugador);
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(AbmJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            ArrayList<Posicion> posiciones = posicionControlador.listar();
            
            modelCombo = new DefaultComboBoxModel(posiciones.toArray());
            jcbPosicion.setModel(modelCombo);
        } catch (Exception ex) {
            Logger.getLogger(AbmJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfId = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfDocumento = new javax.swing.JTextField();
        jtfEdad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListadoJugador = new javax.swing.JTable();
        jbAgregar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jcbPosicion = new javax.swing.JComboBox<>();

        setClosable(true);
        setMaximizable(true);

        jtfId.setToolTipText("");
        jtfId.setEnabled(false);

        jtfApellido.setToolTipText("");

        jtfNombre.setToolTipText("");

        jtfDocumento.setToolTipText("");

        jtfEdad.setToolTipText("");

        jLabel1.setText("ID");

        jLabel2.setText("Apellido");

        jLabel3.setText("Nombre");

        jLabel4.setText("Documento");

        jLabel5.setText("Edad");

        jLabel6.setText("Posicion");

        jtListadoJugador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtListadoJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListadoJugadorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListadoJugador);

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.setToolTipText("");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jcbPosicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDocumento)
                            .addComponent(jtfEdad)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbPosicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbEliminar)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:
        
        Jugador jugador = new Jugador();
                
        if(jtfApellido.getText().length() >= 3 || jtfNombre.getText().length() >= 3 || jtfDocumento.getText().length() >= 3)
        {
            jugador.setApellido(jtfApellido.getText());
            jugador.setNombre(jtfNombre.getText());
            jugador.setDoc(jtfDocumento.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Asegurese de colocar mas de 3 caracteres para guardar");
        }
        
        jugador.setPosicion((Posicion)jcbPosicion.getSelectedItem());
        
        if(Integer.parseInt(jtfEdad.getText()) > 0)
        {
            jugador.setEdad(Integer.parseInt(jtfEdad.getText()));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "introduzca numeros mayores a 0.");
        }
        
        try 
        {
            jugadorControlador.crear(jugador);
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(AbmJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
        try 
        {
            jtListadoJugador.setModel(new GrillaJugador(jugadorControlador.listar()));
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(AbmJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.resetFields();
        this.refreshTable();
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        
        Jugador jugador = new Jugador();
        
        if(jtfApellido.getText().length() >= 3 || jtfNombre.getText().length() >= 3 || jtfDocumento.getText().length() >= 3)
        {
            jugador.setApellido(jtfApellido.getText());
            jugador.setNombre(jtfNombre.getText());
            jugador.setDoc(jtfDocumento.getText());
            jugador.setPosicion((Posicion)jcbPosicion.getSelectedItem());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Asegurese de colocar mas de 3 caracteres para guardar");
        }
        
        jugador.setId(Integer.parseInt(jtfId.getText()));
        jugador.setEdad(Integer.parseInt(jtfEdad.getText()));
                        
        try 
        {
            jugadorControlador.modificar(jugador);
        } 
        catch (Exception ex)
        {
            Logger.getLogger(AbmJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
        try 
        {
            jtListadoJugador.setModel(new GrillaJugador(jugadorControlador.listar()));
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(AbmJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.resetFields();
        this.refreshTable();
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jtListadoJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListadoJugadorMouseClicked
        // TODO add your handling code here:
        
        Jugador jugador = grillaJugador.getJugadorFromRow(jtListadoJugador.getSelectedRow());
        
        jtfId.setText("" + jugador.getId());
        jtfApellido.setText(jugador.getApellido());
        jtfNombre.setText(jugador.getNombre());
        jtfDocumento.setText(jugador.getDoc());
        jtfEdad.setText("" + jugador.getEdad());
        jcbPosicion.setSelectedItem(jugador.getPosicion());
    }//GEN-LAST:event_jtListadoJugadorMouseClicked

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        
        Jugador jugador = new Jugador();
        
        jugador.setId(Integer.parseInt(jtfId.getText()));
        
        try 
        {
            jugadorControlador.eliminar(jugador);
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(AbmJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
        try 
        {
            jtListadoJugador.setModel(new GrillaJugador(jugadorControlador.listar()));
        }
        catch (Exception ex) 
        {
            Logger.getLogger(AbmJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.resetFields();
        this.refreshTable();
    }//GEN-LAST:event_jbEliminarActionPerformed
    
    private void resetFields()
    {    
        jtfId.setText("");
        jtfApellido.setText("");
        jtfNombre.setText("");
        jtfDocumento.setText("");
        jtfEdad.setText("");
    }
    
    private void refreshTable()
    {
        try 
        {
            jtListadoJugador.setModel(new GrillaJugador(jugadorControlador.listar()));
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(AbmJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JComboBox<String> jcbPosicion;
    private javax.swing.JTable jtListadoJugador;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfDocumento;
    private javax.swing.JTextField jtfEdad;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
